### ISSUE TITLE
rds-data-api.json does not show up in windows instance of VS Code

### ISSUE THREAD

**Issue by bvesperman** [indexsoftware/vscode-rds-data-api#10]
I can run this extension just fine on a Mac machine, but it fails quietly on windows. I configure it identical on both machines, run the same sql script, and no results file, rds-data-api.json, shows up.

In the extension area of the VS code under runtime status I see this error:

Uncaught Errors (1)
ENOENT: no such file or directory, open '/tmp/rds-data-api.json'

Attached is a screenshot. It seems like the windows version of the VS Code is trying to use unix style directory structure.

![image](https://user-images.githubusercontent.com/1688102/209990666-8aef9047-c587-4262-a2de-5109bc03a9d9.png)

https://github.com/indexsoftware/vscode-rds-data-api/blob/af5e388d46a3bf8cd2129f7d2c195f964a9d894f/src/providers/OutputProvider.ts#L5

**Comment by joostdelange** [comment]
Hi @bvesperman, you're right, I never tested it on windows while building. I'll take a look at it in the following days.

**Comment by joostdelange** [comment]
@bvesperman just now, I have released a new version with a fix for Windows compatability.
I did a test on the Windows version of vscode and can confirm it's working.
