### ISSUE TITLE
can't select cluster

### ISSUE THREAD

**Issue by diogobaltazar** [indexsoftware/vscode-rds-data-api#12]
Having run ``RDS Data API: Select AWS profile`` (from an already authenticated profile), running the command ``RDS Data API: Select cluster``, the RDS cluster fetching pops up but there's no other feedback, and the vscode status bar shows ``No cluster selected``.

**Comment by joostdelange** [comment]
@diogobaltazar are you sure there are Aurora Serverless V1 clusters in your AWS account, in the region you setup on your profile?
